# This workflow configures the user-statistician to
# generate three SVGs, one each for contribution stats,
# repositories stats, and the language distribution chart, using
# the dark color theme. It uses the image-file input to assign each
# SVG a unique filename. It is configured on a daily
# schedule at 3am.

name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/multiple-stats-cards.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate the stats distribution
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/stats.svg
          colors: dark
          hide-keys: general, repositories, contribTo
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
